name: CI

on: [push]

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        pydantic-version: ["^1.0", "~2.0", "~2.1", "~2.2", "~2.3", "~2.4", "~2.5", "~2.6", "~2.7", "~2.8", "~2.9"]
    with:
      python-version: ${{ matrix.python-version }}
      pydantic-version: ${{ matrix.pydantic-version }}
