name: Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        pydantic-version: ["^1.0", "~2.0", "~2.1", "~2.2", "~2.3", "~2.4", "~2.5", "~2.6", "~2.7", "~2.8", "~2.9"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://install.python-poetry.org | python3 - --version 1.8.3
      - name: Configure poetry
        run: |
          poetry config virtualenvs.create false
      - name: Install dependencies
        run: |
          poetry install --sync --no-interaction
          poetry add pydantic@${{ matrix.pydantic-version }}
          pydantic_version=$(python -c "import pydantic; print(pydantic.__version__)")
          echo "Using pydantic version: ${pydantic_version}"
      - name: Run the code linting
        run: |
          poetry run black --check .
          poetry run isort --check freezeblaster tests
          poetry run mypy freezeblaster
          poetry run pylint --fail-under=9 freezeblaster tests
      - name: Run the unit tests
        run: |
          poetry run pytest -x tests
      - name: Build the library
        run: |
          poetry build

  publish:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    environment:
      name: release
      url: https://pypi.org/project/freezeblaster/
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://install.python-poetry.org | python3 - --version 1.8.3
      - name: Configure poetry
        run: |
          poetry config virtualenvs.create false
      - name: Install dependencies
        run: |
          poetry install --sync --no-interaction
      - name: Build the library
        run: |
          poetry build
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
